# Generated by Django 4.0.5 on 2022-06-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesmodel',
            name='question',
            field=models.TextField(null=True),
        ),
    ]
